spring:
  datasource:
    url: jdbc:mysql://localhost:3306/face?useUnicode=true&characterEncoding=utf-8&characterSetResults=utf-8&serverTimezone=Asia/Seoul
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 10000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        show_sql: true
        id:
          new_generator_mappings: false
  rabbitmq:
    host: localhost
    port: 5672
    username: jaemin
    password: jaemin

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 0
  cache:
    type: redis
    redis:
      use-key-prefix: true
      cache-null-values: true

jwt:
  secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  access-expiration-minutes: 10
  refresh-expiration-days: 1
  access-header-name: Authorization
  refresh-cookie-name: X-Refresh-Token
