name: CD to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-22.04
    
    defaults:
      run:
        working-directory: ./BackEnd
        

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DEV }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy to Dev
        run: |
          kubectl set image deployment/my-spring-app my-spring-app=mydockerhub/myapp:${{ github.sha }} -n dev
          kubectl rollout status deployment/my-spring-app -n dev
