name: Java&Flutter CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
      - "hotfix/**"
      - "dev/**"
      - "fix/**"
      - "feat/**"

jobs:
  build-gradle:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    defaults:
      run:
        working-directory: ./BackEnd

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Give execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Create secret properties file
        run: |
          touch ./src/main/resources/application-secret.properties
          # touch ./src/test/resources/application-secret.properties

      - name: Run Tests Only
        run: ./gradlew clean test

  # flutter-test:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read

  #   defaults:
  #     run:
  #       working-directory: ./Mobile  # Flutter 프로젝트 루트로 수정

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install Flutter SDK
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: "3.29.2"

  #     - name: Install Dependencies
  #       run: flutter pub get

  #     - name: Run Flutter Tests
  #       run: flutter test
