name: springTest

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: contains(github.event.pull_request.changed_files, 'BackEnd/')
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    defaults:
      run:
        working-directory: ./BackEnd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Give execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Create secret properties file
        run: |
          echo "${{ secrets.SPRING_SECRET }}" > ./src/main/resources/application-secret.properties
          echo "${{ secrets.SPRING_TEST_SECRET }}" > ./src/test/resources/application-test.properties
          
      # Test with Gradle
      - name: Test With Gradle
        run: ./gradlew test -i
