name: springCI
#CI는 dev 브랜치에 푸시되면 실행되고, PR은 main 브랜치에 머지될 때 실행됩니다.
on:
  workflow_run:
    workflows: [ "springTest" ]
    types: [ completed ]  # <- 보통 completed 사용
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    defaults:
      run:
        working-directory: ./BackEnd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      # GCP 인증
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_AR_IAM_KEY }}

      # Artifact Registry 연동
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      # Docker Build ()
      - name: Build Docker image
        run: docker build -t asia-northeast3-docker.pkg.dev/jangpyeong/ai-fortune-teller-ar/AIFTSpring:latest .

      # GCP Artifact Registry Push
      - name: Push Docker image to GCP Artifact Registry
        run: docker push asia-northeast3-docker.pkg.dev/jangpyeong/ai-fortune-teller-ar/AIFTSpring:latest
